version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin

     # build the application image
     - run: docker build -t rishabh-docker-twwiw.bintray.io/test/one:onre .

     # deploy the image
     - run:
        name: Login
        command: docker login -u ${BINTRAY_USER} -p ${BINTRAY_API_KEY} https://rishabh-docker-twwiw.bintray.io/v1/auth
     - run:
        name: Push docker container
        command: docker push rishabh-docker-twwiw.bintray.io/test/one:onre
