machine:
  services:
    - docker

dependencies:
  override:
    - scripts/check-env-variables.sh
    - VERSION=0.5.0 scripts/docker-docker.sh build

test:
  override:
    - VERSION=0.5.0 scripts/docker-docker.sh test

deployment:
  bintray:
    owner: packetloop
    branch: [develop]
    commands:
      - VERSION=0.5.0 scripts/docker-docker.sh push
  fork:
    branch: /.*MAYH.*/
    commands:
      - VERSION=0.5.0 scripts/docker-docker.sh push
